#Server
server.port=8081
spring.application.name=user

spring.datasource.url=jdbc:postgresql://localhost:5432/e-comm
#spring.datasource.username=your_username
#spring.datasource.password=your_password
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

#Logging
logging.level.org.springframework=INFO
logging.level.com.yourpackage=DEBUG

#Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

